"""Initial migration.

Revision ID: 9bb6f27af752
Revises: 
Create Date: 2020-06-22 20:16:53.629256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb6f27af752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baby_monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.Boolean(), nullable=False),
    sa.Column('crying', sa.Boolean(), nullable=False),
    sa.Column('sleeping', sa.Boolean(), nullable=False),
    sa.Column('breathing', sa.Boolean(), nullable=False),
    sa.Column('time_no_breathing', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baby_monitor')
    # ### end Alembic commands ###
